### ISSUE TITLE
Problems with responsive display images on blog home page

### ISSUE THREAD

**Issue by bocharsky-bw** [knpuniversity/blog#17]
If browser width less than 1200px images float under right sidebar.

![2015-08-30 11 48 17](https://cloud.githubusercontent.com/assets/3317635/9566447/6d16d5bc-4f0e-11e5-83f8-61da11c861e5.png)

Could we use responsive width for images?

**Comment by weaverryan** [comment]
Good catch, I see it too - ping @Leannapelham!

**Comment by bocharsky-bw** [comment]
Looks like it's fixed now!
